### ISSUE TITLE
Where is the mpa_latest db now?

### ISSUE THREAD

**Issue by iquasere** [biobakery/MetaPhlAn2#1]
It seems for some time now, the databases of MetaPhlan2 have been inaccessible at https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_latest. Running MetaPhlan gives
```
Downloading https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_latest

Warning: Unable to download https://bitbucket.org/biobakery/metaphlan2/downloads/mpa_latest
Traceback (most recent call last):
  File "/opt/conda/bin/metaphlan2.py", line 1442, in <module>
    metaphlan2()
  File "/opt/conda/bin/metaphlan2.py", line 1164, in metaphlan2
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/opt/conda/bin/metaphlan2.py", line 570, in check_and_install_database
    index = resolve_latest_database(bowtie2_db, force_redownload_latest)
  File "/opt/conda/bin/metaphlan2.py", line 549, in resolve_latest_database
    with open(os.path.join(bowtie2_db,'mpa_latest')) as mpa_latest:
FileNotFoundError: [Errno 2] No such file or directory: 'resources_directory/metphlan_dbs/mpa_latest'
```

Where can they be obtained now, so MetaPhlan can be used?

**Comment by iquasere** [comment]
Saw now that the metaphlan package is version 3, and that it works fine. Thank you for the tool, and the continuous improvements!
